services:
  postgres:
    image: postgres:16
    container_name: stockpilot-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: stockpilot
      POSTGRES_PASSWORD: stockpilot123
      POSTGRES_DB: stockpilot

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: stockpilot-backend

    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "3001:3001"

    environment:
      DATABASE_URL: postgresql://stockpilot:stockpilot123@postgres:5432/stockpilot

  frontend:
    build:
      context: ./frontend

    container_name: stockpilot-frontend

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:3000"

volumes:
  postgres_data: